name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Set package version
        run: echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' package.json) > package.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish release candidate
        if: 'github.event.release.prerelease'
        run: npm publish --access public --tag=canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: '!github.event.release.prerelease'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
